### ISSUE TITLE
`External Message Support`: Improve example

### ISSUE THREAD

**Issue by jubnzv** [tact-lang/tact-docs#402] opened 2024-09-27 09:40 UTC
We have the following example:
```
{
  "options": {
    "external": true
  }
}
```

I would write it this way:
```
{
  "projects": [
    {
      "name": "sample",
      ...
      "options": {
        "external": true
      }
    }
  ]
```

In order to additionally highlight that's a part of the project configuration. Otherwise we can have questions: https://t.me/tactlang/41482.

**Comment by novusnota** [comment] 2024-09-27 09:41
A duplicate of tact-lang/tact#1110 (in some sense, since I was planning to re-write it and fix all the issues), but thanks nonetheless!

**Closed as not planned** 2024-09-27 09:42 UTC
Labels: docs: Book
